schema_version = "1.0.0"
id = "eptamat_tools"
name = "Edit Parameters Tool All MATerials"
version = "1.0.0"
tagline = "Edit multiple material parameters across selected objects"
maintainer = "[CPanda]_AKoz <kozirev.ao@gmail.com>"
type = "add-on"
tags = ["Material"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/polykr0t/eptaMat/tree/main"


copyright = [
    "2025 [CPanda]_Akoz",
]
